### ISSUE TITLE
neeeed help with go module

### ISSUE THREAD

**Issue by Hash8395** [reconmap/cli#9]
`root@S-MUT-CYBER:~/cli# make
go build -v -ldflags="-X 'github.com/reconmap/cli/internal/build.BuildVersion=0.9.6'" ./cmd/rmap
go: downloading github.com/fatih/color v1.12.0
go: downloading github.com/urfave/cli/v2 v2.3.0
go: downloading github.com/docker/docker v20.10.8+incompatible
go: downloading github.com/rodaine/table v1.0.1
go: downloading golang.org/x/term v0.0.0-20210615171337-6886f2dfbf5b
go: downloading go.uber.org/zap v1.19.0
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/opencontainers/image-spec v1.0.1
go: downloading golang.org/x/sys v0.0.0-20210809222454-d867a43fc93e
go: downloading go.uber.org/atomic v1.9.0
go: downloading go.uber.org/multierr v1.7.0
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading github.com/containerd/containerd v1.5.5
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading google.golang.org/grpc v1.40.0
go: downloading golang.org/x/net v0.0.0-20210805182204-aaa1db679c0d
go: downloading google.golang.org/genproto v0.0.0-20201110150050-8816d57aaa9a
go: downloading github.com/golang/protobuf v1.5.0
go: downloading google.golang.org/protobuf v1.26.0
go: updates to go.mod needed; to update it:
	go mod tidy
make: *** [Makefile:12: rmap] Error 1`

I have an error with a go mod please can help me ?

**Comment by santiagolizardo** [comment]
Hi @Hash8395 ; Please try again with the latest version of the  code. I have ran `go mod tidy` so let's see if that has made any differences.
Are you running golang 1.17?
Thanks

**Comment by Hash8395** [comment]
it's good thx
